### ISSUE TITLE
'BUFFER_LENGTH' was not declared in this scope

### ISSUE THREAD

**Issue by nima2007** [pkourany/I2CDEV_MPU6050#3]
Veryfing code using this library in Particle Build fails with this error:

```
MPU6050/I2Cdev.cpp:229:62: error: 'BUFFER_LENGTH' was not declared in this scope
             for (uint8_t k = 0
```

**Comment by nielsnl68** [comment]
Same here

**Comment by avigeilpro** [comment]
Same with last firmware (0.4.5), work perfectly with old firmware (0.3.4).

**Comment by pkourany** [comment]
Great!  I'll merge the PR and post an updated library to the IDE later.  Thanks!

**Comment by meltoner** [comment]
Hello perhaps the IDE isn't yet updated?

**Comment by pkourany** [comment]
I could have sworn that I published the update!!!  It is now up on the IDE :)

**Comment by meltoner** [comment]
thanks!
